services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes: []
    command: gunicorn page_project.wsgi:application -b 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-ogc+#iijq3eu3qbkj4!&c96!(z%k(5q*ijpl6-9!87==naks-s"
      - "DJANGO_SECURE_SSL_REDIRECT=False"
      - "DJANGO_SECURE_HSTS_SECONDS=0" 
      - "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS=False" 
      - "DJANGO_SECURE_HSTS_PRELOAD=False" 
      - "DJANGO_SESSION_COOKIE_SECURE=False" 
      - "DJANGO_CSRF_COOKIE_SECURE=False" 